# Generated by Django 3.2.8 on 2021-10-27 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
